status = [ "Bors-CI" ]
timeout_sec = 3600 # 1 hour

# bors will not merge if the PR label exists
block_labels = ["!ci-dont-merge"]

# a PR needs to be approved by defined count of reviewvers
required_approvals = 1

# do not require re-approve after changes
#   very useful on bootstrap developmanet stage only
#   must be set to true later !!!!
up_to_date_approvals = false
